// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>Role of the user</summary>
    public enum IAccountUser_role
    {
        [EnumMember(Value = "admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
        [EnumMember(Value = "accounting")]
        #pragma warning disable CS1591
        Accounting,
        #pragma warning restore CS1591
        [EnumMember(Value = "employee")]
        #pragma warning disable CS1591
        Employee,
        #pragma warning restore CS1591
    }
}
