// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>
    /// Bank statement line details
    /// </summary>
    public class IBankStatementLine : IParsable
    {
        /// <summary>Amount taken out of payment&apos;s fund account</summary>
        public float? Amount { get; set; }
        /// <summary>Currency of the payment&apos;s fund account</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>Date of the payment</summary>
        public DateTimeOffset? Date { get; set; }
        /// <summary>Description of the payment</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Related expenses that are paid via this payment (valid for debit payments only)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExpenseIds { get; set; }
#nullable restore
#else
        public List<string> ExpenseIds { get; set; }
#endif
        /// <summary>Details for an expense payment fees</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public PayhawkSDK.Client.Models.IExpensePaymentFees? Fees { get; set; }
#nullable restore
#else
        public PayhawkSDK.Client.Models.IExpensePaymentFees Fees { get; set; }
#endif
        /// <summary>Unique identifier of payment&apos;s fund account</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FundAccountId { get; set; }
#nullable restore
#else
        public string FundAccountId { get; set; }
#endif
        /// <summary>FX rate of the payment</summary>
        public float? FxRate { get; set; }
        /// <summary>Unique identifier of the bank statement line</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Amount of the payment</summary>
        public float? PaidAmount { get; set; }
        /// <summary>Currency of the payment</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaidCurrency { get; set; }
#nullable restore
#else
        public string PaidCurrency { get; set; }
#endif
        /// <summary>Original identifier of the payment</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentId { get; set; }
#nullable restore
#else
        public string PaymentId { get; set; }
#endif
        /// <summary>Type of the bank statement line</summary>
        public PayhawkSDK.Client.Models.IBankStatementLine_type? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="PayhawkSDK.Client.Models.IBankStatementLine"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static PayhawkSDK.Client.Models.IBankStatementLine CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new PayhawkSDK.Client.Models.IBankStatementLine();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetFloatValue(); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "date", n => { Date = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "expenseIds", n => { ExpenseIds = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                { "fees", n => { Fees = n.GetObjectValue<PayhawkSDK.Client.Models.IExpensePaymentFees>(PayhawkSDK.Client.Models.IExpensePaymentFees.CreateFromDiscriminatorValue); } },
                { "fundAccountId", n => { FundAccountId = n.GetStringValue(); } },
                { "fxRate", n => { FxRate = n.GetFloatValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "paidAmount", n => { PaidAmount = n.GetFloatValue(); } },
                { "paidCurrency", n => { PaidCurrency = n.GetStringValue(); } },
                { "paymentId", n => { PaymentId = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<PayhawkSDK.Client.Models.IBankStatementLine_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteFloatValue("amount", Amount);
            writer.WriteStringValue("currency", Currency);
            writer.WriteDateTimeOffsetValue("date", Date);
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfPrimitiveValues<string>("expenseIds", ExpenseIds);
            writer.WriteObjectValue<PayhawkSDK.Client.Models.IExpensePaymentFees>("fees", Fees);
            writer.WriteStringValue("fundAccountId", FundAccountId);
            writer.WriteFloatValue("fxRate", FxRate);
            writer.WriteStringValue("id", Id);
            writer.WriteFloatValue("paidAmount", PaidAmount);
            writer.WriteStringValue("paidCurrency", PaidCurrency);
            writer.WriteStringValue("paymentId", PaymentId);
            writer.WriteEnumValue<PayhawkSDK.Client.Models.IBankStatementLine_type>("type", Type);
        }
    }
}
