// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>Type of the bank statement line</summary>
    public enum IBankStatementLine_type
    {
        [EnumMember(Value = "debit")]
        #pragma warning disable CS1591
        Debit,
        #pragma warning restore CS1591
        [EnumMember(Value = "credit")]
        #pragma warning disable CS1591
        Credit,
        #pragma warning restore CS1591
    }
}
