// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>Fund account type, for example debit or credit</summary>
    public enum IExpensePayment_fundAccountType
    {
        [EnumMember(Value = "debit")]
        #pragma warning disable CS1591
        Debit,
        #pragma warning restore CS1591
        [EnumMember(Value = "credit")]
        #pragma warning disable CS1591
        Credit,
        #pragma warning restore CS1591
        [EnumMember(Value = "linked")]
        #pragma warning disable CS1591
        Linked,
        #pragma warning restore CS1591
        [EnumMember(Value = "linked_card")]
        #pragma warning disable CS1591
        Linked_card,
        #pragma warning restore CS1591
    }
}
