// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>Type of the expense payment</summary>
    public enum IExpense_type
    {
        [EnumMember(Value = "bank")]
        #pragma warning disable CS1591
        Bank,
        #pragma warning restore CS1591
        [EnumMember(Value = "card")]
        #pragma warning disable CS1591
        Card,
        #pragma warning restore CS1591
        [EnumMember(Value = "cash")]
        #pragma warning disable CS1591
        Cash,
        #pragma warning restore CS1591
        [EnumMember(Value = "cashInAdvance")]
        #pragma warning disable CS1591
        CashInAdvance,
        #pragma warning restore CS1591
        [EnumMember(Value = "mileage")]
        #pragma warning disable CS1591
        Mileage,
        #pragma warning restore CS1591
        [EnumMember(Value = "reimbursable")]
        #pragma warning disable CS1591
        Reimbursable,
        #pragma warning restore CS1591
        [EnumMember(Value = "perDiem")]
        #pragma warning disable CS1591
        PerDiem,
        #pragma warning restore CS1591
    }
}
