// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>Type of the rule, for example rate or deduction</summary>
    public enum IExpensePerDiemAppliedRule_type
    {
        [EnumMember(Value = "Deduction")]
        #pragma warning disable CS1591
        Deduction,
        #pragma warning restore CS1591
        [EnumMember(Value = "Addition")]
        #pragma warning disable CS1591
        Addition,
        #pragma warning restore CS1591
        [EnumMember(Value = "Rate")]
        #pragma warning disable CS1591
        Rate,
        #pragma warning restore CS1591
    }
}
