// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>Type of the payment</summary>
    public enum IExpensePayment_type
    {
        [EnumMember(Value = "bank")]
        #pragma warning disable CS1591
        Bank,
        #pragma warning restore CS1591
        [EnumMember(Value = "card")]
        #pragma warning disable CS1591
        Card,
        #pragma warning restore CS1591
    }
}
