// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>Type of the fund account, for example debit or credit</summary>
    public enum IFundAccount_type
    {
        [EnumMember(Value = "debit")]
        #pragma warning disable CS1591
        Debit,
        #pragma warning restore CS1591
        [EnumMember(Value = "credit")]
        #pragma warning disable CS1591
        Credit,
        #pragma warning restore CS1591
        [EnumMember(Value = "linked")]
        #pragma warning disable CS1591
        Linked,
        #pragma warning restore CS1591
    }
}
