// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>Unit of the purchase order item</summary>
    public enum INewPurchaseOrderItem_units
    {
        [EnumMember(Value = "pieces")]
        #pragma warning disable CS1591
        Pieces,
        #pragma warning restore CS1591
        [EnumMember(Value = "hours")]
        #pragma warning disable CS1591
        Hours,
        #pragma warning restore CS1591
    }
}
