// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>Type of event to subscribe to</summary>
    public enum INewWebhookSubscription_eventType
    {
        [EnumMember(Value = "expense.created")]
        #pragma warning disable CS1591
        ExpenseCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "expense.reviewed")]
        #pragma warning disable CS1591
        ExpenseReviewed,
        #pragma warning restore CS1591
        [EnumMember(Value = "expense.approved")]
        #pragma warning disable CS1591
        ExpenseApproved,
        #pragma warning restore CS1591
        [EnumMember(Value = "expense.deleted")]
        #pragma warning disable CS1591
        ExpenseDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "expense.payment-details.updated")]
        #pragma warning disable CS1591
        ExpensePaymentDetailsUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment.authorized")]
        #pragma warning disable CS1591
        PaymentAuthorized,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment.reverted")]
        #pragma warning disable CS1591
        PaymentReverted,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment.settled")]
        #pragma warning disable CS1591
        PaymentSettled,
        #pragma warning restore CS1591
        [EnumMember(Value = "payment.failed")]
        #pragma warning disable CS1591
        PaymentFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "deposit.received")]
        #pragma warning disable CS1591
        DepositReceived,
        #pragma warning restore CS1591
        [EnumMember(Value = "supplier.created")]
        #pragma warning disable CS1591
        SupplierCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "supplier.updated")]
        #pragma warning disable CS1591
        SupplierUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "purchase-order.status.changed")]
        #pragma warning disable CS1591
        PurchaseOrderStatusChanged,
        #pragma warning restore CS1591
    }
}
