// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>
    /// New purchase order object
    /// </summary>
    public class INewPurchaseOrder : IParsable
    {
        /// <summary>Expense category of the purchase order item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public PayhawkSDK.Client.Models.IObjectReference? CreatedBy { get; set; }
#nullable restore
#else
        public PayhawkSDK.Client.Models.IObjectReference CreatedBy { get; set; }
#endif
        /// <summary>List of purchase order items</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<PayhawkSDK.Client.Models.INewPurchaseOrderItem>? Items { get; set; }
#nullable restore
#else
        public List<PayhawkSDK.Client.Models.INewPurchaseOrderItem> Items { get; set; }
#endif
        /// <summary>Note from the creator of the purchase order</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Note { get; set; }
#nullable restore
#else
        public string Note { get; set; }
#endif
        /// <summary>Purchase Order Number. If not passed, it is autogenerated based on the settings set for the account on approval.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PurchaseOrderNumber { get; set; }
#nullable restore
#else
        public string PurchaseOrderNumber { get; set; }
#endif
        /// <summary>Expense category of the purchase order item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public PayhawkSDK.Client.Models.IObjectReference? Supplier { get; set; }
#nullable restore
#else
        public PayhawkSDK.Client.Models.IObjectReference Supplier { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="PayhawkSDK.Client.Models.INewPurchaseOrder"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static PayhawkSDK.Client.Models.INewPurchaseOrder CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new PayhawkSDK.Client.Models.INewPurchaseOrder();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdBy", n => { CreatedBy = n.GetObjectValue<PayhawkSDK.Client.Models.IObjectReference>(PayhawkSDK.Client.Models.IObjectReference.CreateFromDiscriminatorValue); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<PayhawkSDK.Client.Models.INewPurchaseOrderItem>(PayhawkSDK.Client.Models.INewPurchaseOrderItem.CreateFromDiscriminatorValue)?.ToList(); } },
                { "note", n => { Note = n.GetStringValue(); } },
                { "purchaseOrderNumber", n => { PurchaseOrderNumber = n.GetStringValue(); } },
                { "supplier", n => { Supplier = n.GetObjectValue<PayhawkSDK.Client.Models.IObjectReference>(PayhawkSDK.Client.Models.IObjectReference.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<PayhawkSDK.Client.Models.IObjectReference>("createdBy", CreatedBy);
            writer.WriteCollectionOfObjectValues<PayhawkSDK.Client.Models.INewPurchaseOrderItem>("items", Items);
            writer.WriteStringValue("note", Note);
            writer.WriteStringValue("purchaseOrderNumber", PurchaseOrderNumber);
            writer.WriteObjectValue<PayhawkSDK.Client.Models.IObjectReference>("supplier", Supplier);
        }
    }
}
