// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>Item type of the purchase order</summary>
    public enum IPurchaseOrder_type
    {
        [EnumMember(Value = "normal")]
        #pragma warning disable CS1591
        Normal,
        #pragma warning restore CS1591
        [EnumMember(Value = "receipt_note")]
        #pragma warning disable CS1591
        Receipt_note,
        #pragma warning restore CS1591
    }
}
