// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>Represent the difference between the purchase order total amount and the invoiced amount.</summary>
    public enum IPurchaseOrder_invoicedAmountStatus
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "partial")]
        #pragma warning disable CS1591
        Partial,
        #pragma warning restore CS1591
        [EnumMember(Value = "matched")]
        #pragma warning disable CS1591
        Matched,
        #pragma warning restore CS1591
        [EnumMember(Value = "discrepancy")]
        #pragma warning disable CS1591
        Discrepancy,
        #pragma warning restore CS1591
    }
}
