// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>Bank account type</summary>
    public enum ISupplierBankAccount_accountType
    {
        [EnumMember(Value = "checking")]
        #pragma warning disable CS1591
        Checking,
        #pragma warning restore CS1591
        [EnumMember(Value = "savings")]
        #pragma warning disable CS1591
        Savings,
        #pragma warning restore CS1591
        [EnumMember(Value = "general_ledger")]
        #pragma warning disable CS1591
        General_ledger,
        #pragma warning restore CS1591
        [EnumMember(Value = "loan")]
        #pragma warning disable CS1591
        Loan,
        #pragma warning restore CS1591
    }
}
