// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>Type of the custom field value - free text, a predefined list or a file uploaded previously on Payhawk&apos; platform</summary>
    public enum ISupplierCustomField_type
    {
        [EnumMember(Value = "fixed_list")]
        #pragma warning disable CS1591
        Fixed_list,
        #pragma warning restore CS1591
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "file_upload")]
        #pragma warning disable CS1591
        File_upload,
        #pragma warning restore CS1591
    }
}
