// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>The new status of the supplier</summary>
    public enum ISupplierStatusPatch_status
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "archived")]
        #pragma warning disable CS1591
        Archived,
        #pragma warning restore CS1591
    }
}
