// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>
    /// Supplier custom field object
    /// </summary>
    public class ISupplierCustomField : IParsable
    {
        /// <summary>Unique identifier of the custom field in the external system</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>Unique identifier of the external system</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalSource { get; set; }
#nullable restore
#else
        public string ExternalSource { get; set; }
#endif
        /// <summary>Unique identifier of the supplier custom field</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Indicates if the custom field is always required</summary>
        public bool? IsRequired { get; set; }
        /// <summary>Indicates if the custom field can be edited</summary>
        public bool? IsSystem { get; set; }
        /// <summary>Label of the custom field</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>Type of the custom field value - free text, a predefined list or a file uploaded previously on Payhawk&apos; platform</summary>
        public PayhawkSDK.Client.Models.ISupplierCustomField_type? Type { get; set; }
        /// <summary>List of predefined values to choose from</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<PayhawkSDK.Client.Models.ISupplierCustomFieldValue>? Values { get; set; }
#nullable restore
#else
        public List<PayhawkSDK.Client.Models.ISupplierCustomFieldValue> Values { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="PayhawkSDK.Client.Models.ISupplierCustomField"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static PayhawkSDK.Client.Models.ISupplierCustomField CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new PayhawkSDK.Client.Models.ISupplierCustomField();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "externalId", n => { ExternalId = n.GetStringValue(); } },
                { "externalSource", n => { ExternalSource = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isRequired", n => { IsRequired = n.GetBoolValue(); } },
                { "isSystem", n => { IsSystem = n.GetBoolValue(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<PayhawkSDK.Client.Models.ISupplierCustomField_type>(); } },
                { "values", n => { Values = n.GetCollectionOfObjectValues<PayhawkSDK.Client.Models.ISupplierCustomFieldValue>(PayhawkSDK.Client.Models.ISupplierCustomFieldValue.CreateFromDiscriminatorValue)?.ToList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("externalId", ExternalId);
            writer.WriteStringValue("externalSource", ExternalSource);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isRequired", IsRequired);
            writer.WriteBoolValue("isSystem", IsSystem);
            writer.WriteStringValue("label", Label);
            writer.WriteEnumValue<PayhawkSDK.Client.Models.ISupplierCustomField_type>("type", Type);
            writer.WriteCollectionOfObjectValues<PayhawkSDK.Client.Models.ISupplierCustomFieldValue>("values", Values);
        }
    }
}
