// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>Bank account currency</summary>
    public enum ISupplierBankAccount_currency
    {
        [EnumMember(Value = "EUR")]
        #pragma warning disable CS1591
        EUR,
        #pragma warning restore CS1591
        [EnumMember(Value = "BGN")]
        #pragma warning disable CS1591
        BGN,
        #pragma warning restore CS1591
        [EnumMember(Value = "GBP")]
        #pragma warning disable CS1591
        GBP,
        #pragma warning restore CS1591
        [EnumMember(Value = "USD")]
        #pragma warning disable CS1591
        USD,
        #pragma warning restore CS1591
        [EnumMember(Value = "RON")]
        #pragma warning disable CS1591
        RON,
        #pragma warning restore CS1591
        [EnumMember(Value = "PLN")]
        #pragma warning disable CS1591
        PLN,
        #pragma warning restore CS1591
        [EnumMember(Value = "DKK")]
        #pragma warning disable CS1591
        DKK,
        #pragma warning restore CS1591
        [EnumMember(Value = "AED")]
        #pragma warning disable CS1591
        AED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ARS")]
        #pragma warning disable CS1591
        ARS,
        #pragma warning restore CS1591
        [EnumMember(Value = "AUD")]
        #pragma warning disable CS1591
        AUD,
        #pragma warning restore CS1591
        [EnumMember(Value = "BDT")]
        #pragma warning disable CS1591
        BDT,
        #pragma warning restore CS1591
        [EnumMember(Value = "BRL")]
        #pragma warning disable CS1591
        BRL,
        #pragma warning restore CS1591
        [EnumMember(Value = "BWP")]
        #pragma warning disable CS1591
        BWP,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAD")]
        #pragma warning disable CS1591
        CAD,
        #pragma warning restore CS1591
        [EnumMember(Value = "CHF")]
        #pragma warning disable CS1591
        CHF,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLP")]
        #pragma warning disable CS1591
        CLP,
        #pragma warning restore CS1591
        [EnumMember(Value = "CNY")]
        #pragma warning disable CS1591
        CNY,
        #pragma warning restore CS1591
        [EnumMember(Value = "COP")]
        #pragma warning disable CS1591
        COP,
        #pragma warning restore CS1591
        [EnumMember(Value = "CRC")]
        #pragma warning disable CS1591
        CRC,
        #pragma warning restore CS1591
        [EnumMember(Value = "CZK")]
        #pragma warning disable CS1591
        CZK,
        #pragma warning restore CS1591
        [EnumMember(Value = "EGP")]
        #pragma warning disable CS1591
        EGP,
        #pragma warning restore CS1591
        [EnumMember(Value = "FJD")]
        #pragma warning disable CS1591
        FJD,
        #pragma warning restore CS1591
        [EnumMember(Value = "GEL")]
        #pragma warning disable CS1591
        GEL,
        #pragma warning restore CS1591
        [EnumMember(Value = "GHS")]
        #pragma warning disable CS1591
        GHS,
        #pragma warning restore CS1591
        [EnumMember(Value = "HKD")]
        #pragma warning disable CS1591
        HKD,
        #pragma warning restore CS1591
        [EnumMember(Value = "HUF")]
        #pragma warning disable CS1591
        HUF,
        #pragma warning restore CS1591
        [EnumMember(Value = "IDR")]
        #pragma warning disable CS1591
        IDR,
        #pragma warning restore CS1591
        [EnumMember(Value = "ILS")]
        #pragma warning disable CS1591
        ILS,
        #pragma warning restore CS1591
        [EnumMember(Value = "INR")]
        #pragma warning disable CS1591
        INR,
        #pragma warning restore CS1591
        [EnumMember(Value = "JPY")]
        #pragma warning disable CS1591
        JPY,
        #pragma warning restore CS1591
        [EnumMember(Value = "KES")]
        #pragma warning disable CS1591
        KES,
        #pragma warning restore CS1591
        [EnumMember(Value = "KRW")]
        #pragma warning disable CS1591
        KRW,
        #pragma warning restore CS1591
        [EnumMember(Value = "LKR")]
        #pragma warning disable CS1591
        LKR,
        #pragma warning restore CS1591
        [EnumMember(Value = "MAD")]
        #pragma warning disable CS1591
        MAD,
        #pragma warning restore CS1591
        [EnumMember(Value = "MXN")]
        #pragma warning disable CS1591
        MXN,
        #pragma warning restore CS1591
        [EnumMember(Value = "MYR")]
        #pragma warning disable CS1591
        MYR,
        #pragma warning restore CS1591
        [EnumMember(Value = "NGN")]
        #pragma warning disable CS1591
        NGN,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOK")]
        #pragma warning disable CS1591
        NOK,
        #pragma warning restore CS1591
        [EnumMember(Value = "NPR")]
        #pragma warning disable CS1591
        NPR,
        #pragma warning restore CS1591
        [EnumMember(Value = "NZD")]
        #pragma warning disable CS1591
        NZD,
        #pragma warning restore CS1591
        [EnumMember(Value = "PHP")]
        #pragma warning disable CS1591
        PHP,
        #pragma warning restore CS1591
        [EnumMember(Value = "PKR")]
        #pragma warning disable CS1591
        PKR,
        #pragma warning restore CS1591
        [EnumMember(Value = "RUB")]
        #pragma warning disable CS1591
        RUB,
        #pragma warning restore CS1591
        [EnumMember(Value = "SEK")]
        #pragma warning disable CS1591
        SEK,
        #pragma warning restore CS1591
        [EnumMember(Value = "SGD")]
        #pragma warning disable CS1591
        SGD,
        #pragma warning restore CS1591
        [EnumMember(Value = "THB")]
        #pragma warning disable CS1591
        THB,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRY")]
        #pragma warning disable CS1591
        TRY,
        #pragma warning restore CS1591
        [EnumMember(Value = "TZS")]
        #pragma warning disable CS1591
        TZS,
        #pragma warning restore CS1591
        [EnumMember(Value = "UAH")]
        #pragma warning disable CS1591
        UAH,
        #pragma warning restore CS1591
        [EnumMember(Value = "UGX")]
        #pragma warning disable CS1591
        UGX,
        #pragma warning restore CS1591
        [EnumMember(Value = "UYU")]
        #pragma warning disable CS1591
        UYU,
        #pragma warning restore CS1591
        [EnumMember(Value = "VND")]
        #pragma warning disable CS1591
        VND,
        #pragma warning restore CS1591
        [EnumMember(Value = "XOF")]
        #pragma warning disable CS1591
        XOF,
        #pragma warning restore CS1591
        [EnumMember(Value = "ZAR")]
        #pragma warning disable CS1591
        ZAR,
        #pragma warning restore CS1591
        [EnumMember(Value = "ZMW")]
        #pragma warning disable CS1591
        ZMW,
        #pragma warning restore CS1591
    }
}
