// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayhawkSDK.Client.Models
{
    #pragma warning disable CS1591
    public enum ITeamMember_roles
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "employee")]
        #pragma warning disable CS1591
        Employee,
        #pragma warning restore CS1591
        [EnumMember(Value = "manager")]
        #pragma warning disable CS1591
        Manager,
        #pragma warning restore CS1591
    }
}
