// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayhawkSDK.Client.Models
{
    /// <summary>Status of the webhook subscription</summary>
    public enum IWebhookSubscription_status
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "deactivated_by_payhawk")]
        #pragma warning disable CS1591
        Deactivated_by_payhawk,
        #pragma warning restore CS1591
        [EnumMember(Value = "deactivated_by_user")]
        #pragma warning disable CS1591
        Deactivated_by_user,
        #pragma warning restore CS1591
    }
}
