// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using PayhawkSDK.Client.Api.V3.Accounts;
using PayhawkSDK.Client.Api.V3.Groups;
using PayhawkSDK.Client.Api.V3.RsaPublicKey;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace PayhawkSDK.Client.Api.V3
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v3
    /// </summary>
    public class V3RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The accounts property</summary>
        public PayhawkSDK.Client.Api.V3.Accounts.AccountsRequestBuilder Accounts
        {
            get => new PayhawkSDK.Client.Api.V3.Accounts.AccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The groups property</summary>
        public PayhawkSDK.Client.Api.V3.Groups.GroupsRequestBuilder Groups
        {
            get => new PayhawkSDK.Client.Api.V3.Groups.GroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rsaPublicKey property</summary>
        public PayhawkSDK.Client.Api.V3.RsaPublicKey.RsaPublicKeyRequestBuilder RsaPublicKey
        {
            get => new PayhawkSDK.Client.Api.V3.RsaPublicKey.RsaPublicKeyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="PayhawkSDK.Client.Api.V3.V3RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V3RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="PayhawkSDK.Client.Api.V3.V3RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V3RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v3", rawUrl)
        {
        }
    }
}
